# Generated by Django 3.0.1 on 2020-04-27 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='choose any username', max_length=100)),
                ('post_content', models.TextField(default='post about anything you want, please try to keep it polite', max_length=500)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='twitter egg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='choose any username', max_length=100, verbose_name='username')),
                ('comment_content', models.TextField(default='say anything you want, please try to keep it polite', max_length=250)),
                ('timestamp', models.TimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.BlogPost')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.User')),
            ],
        ),
    ]
