# Generated by Django 3.0.1 on 2020-05-07 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='choose any username', max_length=100)),
                ('post_content', models.TextField(default='type your post here', max_length=500)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='username', max_length=125)),
                ('comment_content', models.TextField(default='type your comment here', max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.BlogPost')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
