# Generated by Django 3.0.1 on 2020-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.TextField(default='username', max_length=125),
        ),
    ]
