# Generated by Django 3.0.1 on 2020-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('fu', 'fu'), ('da', 'da'), ('sh', 'sh'), ('other', 'other')], default='other', max_length=10),
        ),
    ]
