# Generated by Django 3.0.1 on 2020-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('sp', 'sports'), ('news', 'news'), ('computer science', 'computers'), ('fin', 'finance'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
